sudo: required
language: java
install: true
jdk:
  - oraclejdk8
env:
  global:
    - XDG_RUNTIME_DIR="/tmp"

# GUI is required for eclipse testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
 - mvn clean install

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

after_failure: 
- cat /home/travis/build/bmaggi/SysML14-Gendoc-Example/com.github.bmaggi.sysml14.gendoc.queries.tests/target/work/configuration/1522095457650.log
